// File generated by hand from the Firebase config files for project
// `nadif-app-d19f3` (google-services.json / GoogleService-Info.plist).
// Mirrors the shape of FlutterFire CLI output so it can be regenerated with
// `flutterfire configure` later if desired.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform: '
          '$defaultTargetPlatform',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4udXWEv5sH691OQTOx_EJdF3jaSrd3J4',
    appId: '1:457823581164:android:41dc446797f342733186c9',
    messagingSenderId: '457823581164',
    projectId: 'nadif-app-d19f3',
    storageBucket: 'nadif-app-d19f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7x7-bHwBFcogU59IRnmdirVEoBkx4hCY',
    appId: '1:457823581164:ios:e2621a7bf0a359343186c9',
    messagingSenderId: '457823581164',
    projectId: 'nadif-app-d19f3',
    storageBucket: 'nadif-app-d19f3.firebasestorage.app',
    iosBundleId: 'com.nadif.app',
  );
}
