import type { Metadata } from 'next';
import LegalDoc, { type LegalDocContent } from '../components/legal/LegalDoc';
import { SITE_INFO, type LegalLang } from '../lib/site-info';

export const metadata: Metadata = {
  title: 'Privacy Policy — Nadif',
  description:
    'How the Nadif mobile app and website collect, use, share and protect your personal data, and how to exercise your privacy rights.',
  alternates: { canonical: `${SITE_INFO.siteUrl}/privacy-policy` },
};

const doc: Record<LegalLang, LegalDocContent> = {
  EN: {
    title: 'Privacy Policy',
    subtitle:
      'This policy explains what personal data the Nadif mobile application and website collect, why we need it, who it is shared with, and how you can delete it.',
    intro: `${SITE_INFO.legalName} ("Nadif", "we", "us") operates the Nadif home cleaning and laundry service, the Nadif mobile application (Android package ${SITE_INFO.androidPackage}) and this website. We only collect the data required to take your booking, send a cleaning agent to your home and support you afterwards. We never sell your personal data.`,
    sections: [
      {
        heading: 'Data we collect',
        paragraphs: ['We collect the following categories of personal data, all of them provided by you or generated by your use of the app:'],
        bullets: [
          'Account data: full name, mobile phone number, email address and a password (stored only as an irreversible hash). When you sign up with your phone number we also send and verify a one-time code (OTP).',
          'Service address and location: the address you type for a booking, plus the GPS coordinates of the pin you place on the map. Location is only read when you choose to use the map to locate your home.',
          'Booking data: selected service or category, surface area, number of extra workers, cleaning materials and product options, requested date and time, express (Service Rapide) option, promo code, your notes to the team, price and order status.',
          'Photos you upload: pictures of the rooms or items to be cleaned, when you choose to attach them to an order or a subscription request.',
          'Subscription data: property type, surface, number of rooms, chosen plan, scheduled sessions and payments recorded by our team.',
          'Device notification token: a Firebase Cloud Messaging identifier used to send you push notifications about your order status.',
          'Support messages: the content of the messages you send us by email, by phone or through the contact form on this website.',
        ],
      },
      {
        heading: 'How we use your data',
        bullets: [
          'Create and manage your account and keep you signed in securely.',
          'Take, price, schedule and fulfil your cleaning, laundry and subscription orders.',
          'Give the assigned cleaning agent the address, access notes and photos needed to perform the service at your home.',
          'Notify you (push notification, and email or phone where relevant) when your order is confirmed, in progress, completed or cancelled.',
          'Apply promo codes and calculate the amount due.',
          'Answer your support requests and resolve disputes or incidents.',
          'Keep the service secure, prevent abuse and fraudulent bookings, and comply with our legal obligations in Algeria.',
        ],
      },
      {
        heading: 'Permissions the app requests',
        bullets: [
          'Location (approximate and precise): used only to centre the booking map on your position and to attach coordinates to your order so the agent can find your home. You can refuse it and type your address manually.',
          'Notifications: used to inform you about the status of your orders and subscription sessions. You can turn notifications off at any time in your device settings.',
          'Photos / camera roll: used only when you choose to attach pictures to an order or a subscription request.',
        ],
        callout: 'Permissions can be withdrawn at any time from your Android or iOS system settings. The app remains usable, but map-based address selection and status notifications will be limited.',
      },
      {
        heading: 'Who we share data with',
        paragraphs: ['We do not sell, rent or trade your personal data. We share it only in the following situations:'],
        bullets: [
          'Cleaning agents and staff assigned to your order, who receive your name, phone number, address, notes and any photos attached — strictly for the purpose of performing the service.',
          'Google Firebase Cloud Messaging, which delivers push notifications to your device.',
          'Our email delivery provider, used to send transactional messages such as order confirmations and administrative alerts.',
          'Our hosting provider, which stores the application database and uploaded images on secured servers.',
          'Competent authorities, where disclosure is required by applicable Algerian law or a valid legal request.',
        ],
      },
      {
        heading: 'No advertising or tracking',
        paragraphs: [
          'The Nadif app contains no advertising network, no third-party advertising identifier and no behavioural tracking SDK. We do not build advertising profiles and we do not share your data with data brokers.',
        ],
      },
      {
        heading: 'How long we keep your data',
        bullets: [
          'Account data is kept for as long as your account exists.',
          'Order and subscription records are kept while your account exists, so you can consult your history and so we can handle after-service claims.',
          'Uploaded photos are kept with the related order.',
          'When you delete your account, the data listed above is permanently erased from our live database. Residual copies in encrypted backups are purged within 30 days.',
        ],
      },
      {
        heading: 'Your rights and how to delete your account',
        paragraphs: [
          'You may at any time access your data, correct it, or request its complete deletion. Your profile is editable directly in the app, and you can delete your account and all associated data yourself from the app — see our dedicated page for step-by-step instructions.',
          `If you prefer, write to us at ${SITE_INFO.privacyEmail} from the email address or phone number registered on your account, and we will process your request within 30 days.`,
        ],
        callout: `Account deletion instructions: ${SITE_INFO.siteUrl}/delete-account`,
      },
      {
        heading: 'Security',
        paragraphs: [
          'All traffic between the app, this website and our servers is encrypted in transit (HTTPS). Passwords are stored only as salted hashes and are never readable by our staff. Access to the administration back office is restricted to authenticated administrators, and authentication tokens are stored in your device secure storage.',
          'No system is perfectly secure. If a breach affecting your personal data occurs, we will inform the affected users and the competent authority without undue delay.',
        ],
      },
      {
        heading: "Children's privacy",
        paragraphs: [
          'The Nadif service is intended for adults. We do not knowingly collect personal data from children under 18. If you believe a minor has created an account, contact us and we will delete it.',
        ],
      },
      {
        heading: 'Changes to this policy',
        paragraphs: [
          'We may update this policy to reflect changes to the service or to the law. The date at the top of this page always indicates the current version. Significant changes will be announced in the app or by email.',
        ],
      },
      {
        heading: 'Contact us',
        paragraphs: [
          `For any question about this policy or about your personal data: ${SITE_INFO.privacyEmail} — ${SITE_INFO.phoneDisplay} — ${SITE_INFO.legalName}, ${SITE_INFO.address.EN}.`,
        ],
      },
    ],
  },

  FR: {
    title: 'Politique de confidentialité',
    subtitle:
      "Cette politique explique quelles données personnelles l'application mobile Nadif et ce site collectent, pourquoi nous en avons besoin, avec qui elles sont partagées et comment les supprimer.",
    intro: `${SITE_INFO.legalName} (« Nadif », « nous ») exploite le service de nettoyage à domicile et de pressing Nadif, l'application mobile Nadif (package Android ${SITE_INFO.androidPackage}) et ce site web. Nous ne collectons que les données nécessaires pour enregistrer votre réservation, envoyer un agent de nettoyage à votre domicile et vous accompagner ensuite. Nous ne vendons jamais vos données personnelles.`,
    sections: [
      {
        heading: 'Données que nous collectons',
        paragraphs: ['Nous collectons les catégories de données suivantes, toutes fournies par vous ou générées par votre utilisation de l\'application :'],
        bullets: [
          "Données de compte : nom et prénom, numéro de téléphone mobile, adresse e-mail et mot de passe (conservé uniquement sous forme de hachage irréversible). Lors d'une inscription par téléphone, nous envoyons et vérifions également un code à usage unique (OTP).",
          "Adresse d'intervention et localisation : l'adresse que vous saisissez pour une réservation, ainsi que les coordonnées GPS du point que vous placez sur la carte. La localisation n'est lue que si vous choisissez d'utiliser la carte pour situer votre domicile.",
          "Données de réservation : service ou catégorie choisi, surface, nombre d'agents supplémentaires, options de matériel et de produits, date et heure souhaitées, option express (Service Rapide), code promo, vos notes pour l'équipe, prix et statut de la commande.",
          "Photos que vous téléchargez : images des pièces ou des articles à nettoyer, lorsque vous choisissez de les joindre à une commande ou à une demande d'abonnement.",
          "Données d'abonnement : type de bien, surface, nombre de pièces à nettoyer, formule choisie, séances planifiées et paiements enregistrés par notre équipe.",
          "Jeton de notification de l'appareil : un identifiant Firebase Cloud Messaging utilisé pour vous envoyer des notifications push sur le statut de votre commande.",
          "Messages de support : le contenu des messages que vous nous adressez par e-mail, par téléphone ou via le formulaire de contact de ce site.",
        ],
      },
      {
        heading: 'Utilisation de vos données',
        bullets: [
          'Créer et gérer votre compte et vous maintenir connecté de façon sécurisée.',
          "Enregistrer, tarifer, planifier et exécuter vos commandes de nettoyage, de pressing et d'abonnement.",
          "Transmettre à l'agent assigné l'adresse, les consignes d'accès et les photos nécessaires à la réalisation de la prestation à votre domicile.",
          'Vous informer (notification push, et e-mail ou téléphone le cas échéant) lorsque votre commande est confirmée, en cours, terminée ou annulée.',
          'Appliquer les codes promo et calculer le montant dû.',
          'Répondre à vos demandes de support et traiter les litiges ou incidents.',
          'Assurer la sécurité du service, prévenir les abus et les réservations frauduleuses, et respecter nos obligations légales en Algérie.',
        ],
      },
      {
        heading: "Autorisations demandées par l'application",
        bullets: [
          "Localisation (approximative et précise) : utilisée uniquement pour centrer la carte de réservation sur votre position et joindre les coordonnées à votre commande afin que l'agent trouve votre domicile. Vous pouvez la refuser et saisir votre adresse manuellement.",
          "Notifications : utilisées pour vous informer du statut de vos commandes et de vos séances d'abonnement. Vous pouvez les désactiver à tout moment dans les réglages de votre appareil.",
          "Photos / galerie : utilisées uniquement lorsque vous choisissez de joindre des images à une commande ou à une demande d'abonnement.",
        ],
        callout: "Les autorisations peuvent être retirées à tout moment depuis les réglages système Android ou iOS. L'application reste utilisable, mais la sélection d'adresse sur la carte et les notifications de statut seront limitées.",
      },
      {
        heading: 'Avec qui nous partageons les données',
        paragraphs: ['Nous ne vendons, ne louons et n\'échangeons pas vos données personnelles. Nous les partageons uniquement dans les cas suivants :'],
        bullets: [
          "Les agents de nettoyage et le personnel assignés à votre commande, qui reçoivent votre nom, votre numéro de téléphone, votre adresse, vos notes et les photos jointes — strictement pour réaliser la prestation.",
          'Google Firebase Cloud Messaging, qui délivre les notifications push sur votre appareil.',
          "Notre prestataire d'envoi d'e-mails, utilisé pour les messages transactionnels tels que les confirmations de commande et les alertes administratives.",
          "Notre hébergeur, qui stocke la base de données de l'application et les images téléchargées sur des serveurs sécurisés.",
          "Les autorités compétentes, lorsque la communication est exigée par la loi algérienne applicable ou par une demande légale valide.",
        ],
      },
      {
        heading: 'Aucune publicité ni pistage',
        paragraphs: [
          "L'application Nadif ne contient aucune régie publicitaire, aucun identifiant publicitaire tiers et aucun SDK de pistage comportemental. Nous ne constituons pas de profils publicitaires et ne transmettons pas vos données à des courtiers en données.",
        ],
      },
      {
        heading: 'Durée de conservation',
        bullets: [
          'Les données de compte sont conservées aussi longtemps que votre compte existe.',
          "Les commandes et abonnements sont conservés pendant la vie de votre compte, afin que vous puissiez consulter votre historique et que nous puissions traiter les réclamations après service.",
          'Les photos téléchargées sont conservées avec la commande correspondante.',
          "Lorsque vous supprimez votre compte, les données ci-dessus sont effacées définitivement de notre base de production. Les copies résiduelles présentes dans les sauvegardes chiffrées sont purgées sous 30 jours.",
        ],
      },
      {
        heading: 'Vos droits et suppression du compte',
        paragraphs: [
          "Vous pouvez à tout moment accéder à vos données, les rectifier ou demander leur suppression complète. Votre profil est modifiable directement dans l'application, et vous pouvez supprimer vous-même votre compte et toutes les données associées depuis l'application — voir notre page dédiée pour la procédure détaillée.",
          `Si vous préférez, écrivez-nous à ${SITE_INFO.privacyEmail} depuis l'adresse e-mail ou le numéro de téléphone enregistré sur votre compte : nous traiterons votre demande sous 30 jours.`,
        ],
        callout: `Procédure de suppression du compte : ${SITE_INFO.siteUrl}/delete-account`,
      },
      {
        heading: 'Sécurité',
        paragraphs: [
          "Tous les échanges entre l'application, ce site et nos serveurs sont chiffrés en transit (HTTPS). Les mots de passe sont conservés uniquement sous forme de hachages salés et ne sont jamais lisibles par notre personnel. L'accès au back-office d'administration est réservé aux administrateurs authentifiés, et les jetons d'authentification sont stockés dans le stockage sécurisé de votre appareil.",
          "Aucun système n'est parfaitement sûr. En cas de violation affectant vos données personnelles, nous informerons les utilisateurs concernés et l'autorité compétente dans les meilleurs délais.",
        ],
      },
      {
        heading: 'Protection des mineurs',
        paragraphs: [
          "Le service Nadif est destiné aux adultes. Nous ne collectons pas sciemment de données concernant des personnes de moins de 18 ans. Si vous pensez qu'un mineur a créé un compte, contactez-nous et nous le supprimerons.",
        ],
      },
      {
        heading: 'Modifications de cette politique',
        paragraphs: [
          "Nous pouvons mettre à jour cette politique pour refléter des évolutions du service ou de la réglementation. La date en haut de cette page indique toujours la version en vigueur. Les changements significatifs seront annoncés dans l'application ou par e-mail.",
        ],
      },
      {
        heading: 'Nous contacter',
        paragraphs: [
          `Pour toute question sur cette politique ou sur vos données personnelles : ${SITE_INFO.privacyEmail} — ${SITE_INFO.phoneDisplay} — ${SITE_INFO.legalName}, ${SITE_INFO.address.FR}.`,
        ],
      },
    ],
  },

  AR: {
    title: 'سياسة الخصوصية',
    subtitle:
      'توضح هذه السياسة البيانات الشخصية التي يجمعها تطبيق نظيف وهذا الموقع، وسبب حاجتنا إليها، ومع من تُشارَك، وكيف يمكنك حذفها.',
    intro: `تُشغّل ${SITE_INFO.legalName} (« نظيف ») خدمة تنظيف المنازل والغسيل، وتطبيق نظيف للهواتف (حزمة أندرويد ${SITE_INFO.androidPackage})، وهذا الموقع الإلكتروني. نحن نجمع فقط البيانات اللازمة لتسجيل حجزك وإرسال عامل تنظيف إلى منزلك ومتابعتك بعد الخدمة. ولا نبيع بياناتك الشخصية أبداً.`,
    sections: [
      {
        heading: 'البيانات التي نجمعها',
        paragraphs: ['نجمع فئات البيانات الشخصية التالية، وكلها تقدمها أنت أو تنتج عن استخدامك للتطبيق:'],
        bullets: [
          'بيانات الحساب: الاسم الكامل، رقم الهاتف المحمول، البريد الإلكتروني، وكلمة المرور (تُخزَّن فقط في صورة مشفّرة غير قابلة للعكس). عند التسجيل برقم الهاتف نرسل أيضاً رمزاً لمرة واحدة (OTP) للتحقق.',
          'عنوان الخدمة والموقع: العنوان الذي تكتبه للحجز، وإحداثيات GPS للنقطة التي تحددها على الخريطة. لا تُقرأ بيانات الموقع إلا إذا اخترت استخدام الخريطة لتحديد منزلك.',
          'بيانات الحجز: الخدمة أو الفئة المختارة، المساحة، عدد العمال الإضافيين، خيارات المواد والمنتجات، التاريخ والوقت المطلوبان، خيار الخدمة السريعة، رمز الخصم، ملاحظاتك للفريق، السعر وحالة الطلب.',
          'الصور التي ترفعها: صور الغرف أو الأغراض المطلوب تنظيفها، عندما تختار إرفاقها بطلب أو بطلب اشتراك.',
          'بيانات الاشتراك: نوع العقار، المساحة، عدد الغرف، الباقة المختارة، الجلسات المبرمجة والمدفوعات التي يسجلها فريقنا.',
          'رمز الإشعارات الخاص بالجهاز: معرّف Firebase Cloud Messaging يُستخدم لإرسال إشعارات حول حالة طلبك.',
          'رسائل الدعم: محتوى الرسائل التي ترسلها إلينا بالبريد الإلكتروني أو الهاتف أو عبر نموذج الاتصال في هذا الموقع.',
        ],
      },
      {
        heading: 'كيف نستخدم بياناتك',
        bullets: [
          'إنشاء حسابك وإدارته والحفاظ على تسجيل دخولك بشكل آمن.',
          'تسجيل طلبات التنظيف والغسيل والاشتراكات وتحديد أسعارها وبرمجتها وتنفيذها.',
          'تزويد العامل المكلّف بالعنوان وملاحظات الوصول والصور اللازمة لتنفيذ الخدمة في منزلك.',
          'إبلاغك (بإشعار، وبالبريد الإلكتروني أو الهاتف عند الحاجة) عند تأكيد طلبك أو بدء تنفيذه أو إتمامه أو إلغائه.',
          'تطبيق رموز الخصم وحساب المبلغ المستحق.',
          'الرد على طلبات الدعم ومعالجة الشكاوى والحوادث.',
          'الحفاظ على أمن الخدمة ومنع الاستخدام السيئ والحجوزات الوهمية، والوفاء بالتزاماتنا القانونية في الجزائر.',
        ],
      },
      {
        heading: 'الأذونات التي يطلبها التطبيق',
        bullets: [
          'الموقع (التقريبي والدقيق): يُستخدم فقط لتوسيط خريطة الحجز على موقعك وإرفاق الإحداثيات بطلبك حتى يجد العامل منزلك. يمكنك رفضه وكتابة عنوانك يدوياً.',
          'الإشعارات: تُستخدم لإبلاغك بحالة طلباتك وجلسات اشتراكك. يمكنك تعطيلها في أي وقت من إعدادات جهازك.',
          'الصور / المعرض: تُستخدم فقط عندما تختار إرفاق صور بطلب أو بطلب اشتراك.',
        ],
        callout: 'يمكن سحب الأذونات في أي وقت من إعدادات نظام أندرويد أو iOS. يبقى التطبيق قابلاً للاستخدام، لكن تحديد العنوان على الخريطة وإشعارات الحالة ستكون محدودة.',
      },
      {
        heading: 'مع من نشارك البيانات',
        paragraphs: ['نحن لا نبيع بياناتك الشخصية ولا نؤجرها ولا نتبادلها. ونشاركها فقط في الحالات التالية:'],
        bullets: [
          'عمال التنظيف والموظفون المكلفون بطلبك، ويحصلون على اسمك ورقم هاتفك وعنوانك وملاحظاتك والصور المرفقة — لغرض تنفيذ الخدمة فقط.',
          'خدمة Google Firebase Cloud Messaging التي توصل الإشعارات إلى جهازك.',
          'مزود إرسال البريد الإلكتروني، للرسائل المعاملاتية مثل تأكيدات الطلبات والتنبيهات الإدارية.',
          'مزود الاستضافة الذي يخزّن قاعدة بيانات التطبيق والصور المرفوعة على خدمات آمنة.',
          'السلطات المختصة، عندما يكون الإفصاح مطلوباً بموجب القانون الجزائري المعمول به أو طلب قانوني صحيح.',
        ],
      },
      {
        heading: 'لا إعلانات ولا تتبع',
        paragraphs: [
          'لا يحتوي تطبيق نظيف على أي شبكة إعلانات ولا معرّف إعلاني تابع لجهة خارجية ولا أي أداة تتبع سلوكي. نحن لا نبني ملفات إعلانية ولا نمرر بياناتك إلى وسطاء البيانات.',
        ],
      },
      {
        heading: 'مدة الاحتفاظ بالبيانات',
        bullets: [
          'تُحفظ بيانات الحساب طالما بقي حسابك قائماً.',
          'تُحفظ الطلبات والاشتراكات طوال مدة وجود حسابك، حتى تتمكن من مراجعة سجلك ونتمكن من معالجة الشكاوى بعد الخدمة.',
          'تُحفظ الصور المرفوعة مع الطلب المرتبط بها.',
          'عند حذف حسابك، تُمحى البيانات المذكورة أعلاه نهائياً من قاعدة بياناتنا التشغيلية، وتُزال النسخ المتبقية في النسخ الاحتياطية المشفّرة في غضون 30 يوماً.',
        ],
      },
      {
        heading: 'حقوقك وحذف الحساب',
        paragraphs: [
          'يمكنك في أي وقت الوصول إلى بياناتك أو تصحيحها أو طلب حذفها بالكامل. ملفك الشخصي قابل للتعديل مباشرة في التطبيق، ويمكنك حذف حسابك وكل البيانات المرتبطة به بنفسك من التطبيق — راجع صفحتنا المخصصة للخطوات التفصيلية.',
          `وإن فضّلت، راسلنا على ${SITE_INFO.privacyEmail} من البريد الإلكتروني أو رقم الهاتف المسجّل في حسابك، وسنعالج طلبك في غضون 30 يوماً.`,
        ],
        callout: `خطوات حذف الحساب: ${SITE_INFO.siteUrl}/delete-account`,
      },
      {
        heading: 'الأمن',
        paragraphs: [
          'جميع الاتصالات بين التطبيق وهذا الموقع وخدماتنا مشفّرة أثناء النقل (HTTPS). تُخزَّن كلمات المرور في صورة مشفّرة مملّحة فقط ولا يمكن لأي من موظفينا قراءتها. الوصول إلى لوحة الإدارة محصور بالمسؤولين المصرّح لهم، وتُخزَّن رموز المصادقة في الذاكرة الآمنة لجهازك.',
          'لا يوجد نظام آمن بشكل مطلق. في حال وقوع اختراق يمس بياناتك الشخصية، سنُبلغ المستخدمين المعنيين والسلطة المختصة دون تأخير غير مبرر.',
        ],
      },
      {
        heading: 'خصوصية الأطفال',
        paragraphs: [
          'خدمة نظيف مخصّصة للبالغين. ونحن لا نجمع عن قصد بيانات شخصية لمن هم دون 18 سنة. إذا كنت تعتقد أن قاصراً أنشأ حساباً، فاتصل بنا وسنحذفه.',
        ],
      },
      {
        heading: 'تعديلات هذه السياسة',
        paragraphs: [
          'قد نحدّث هذه السياسة لتعكس تغييرات في الخدمة أو في القانون. ويشير التاريخ في أعلى الصفحة دائماً إلى النسخة السارية. وسيتم الإعلان عن التغييرات الجوهرية في التطبيق أو بالبريد الإلكتروني.',
        ],
      },
      {
        heading: 'اتصل بنا',
        paragraphs: [
          `لأي سؤال بخصوص هذه السياسة أو بياناتك الشخصية: ${SITE_INFO.privacyEmail} — ${SITE_INFO.phoneDisplay} — ${SITE_INFO.legalName}، ${SITE_INFO.address.AR}.`,
        ],
      },
    ],
  },
};

export default function PrivacyPolicyPage() {
  return <LegalDoc doc={doc} defaultLang="FR" />;
}
